# prometheus/prometheus.yml
global:
  scrape_interval: 10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'kafka-brokers'
    static_configs:
      - targets: ['broker1:7071', 'broker2:7071', 'broker3:7071']
        labels:
          env: 'demo'
          cluster: 'message-format-test'

  - job_name: 'schema-registry'
    static_configs:
      - targets: ['schema-registry:7071']
        labels:
          env: 'demo'

  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']
